'use strict';

const C = require('./aiTaskContractV2.cjs');
const { validateSourceConflictV1, validateSourceConfigComparisonV1, validateSourceEvidenceRecordV1 } = require('./aiTaskDocumentsV2.cjs');
class AiTaskValidationError extends Error { constructor(code) { super(code); this.name = 'AiTaskValidationError'; this.code = code; } }
const fail = code => { throw new AiTaskValidationError(code); };
const has = (object, key) => Object.prototype.hasOwnProperty.call(object || {}, key);
const object = (value, code) => { if (!value || typeof value !== 'object' || Array.isArray(value)) fail(code); return value; };
const array = (value, min, max, code) => { if (!Array.isArray(value) || value.length < min || value.length > max) fail(code); return value; };
const string = (value, min, max, code) => { if (typeof value !== 'string' || value.length < min || value.length > max) fail(code); return value; };
const nullableString = (value, min, max, code) => { if (value !== null) string(value, min, max, code); };
const finite = (value, code) => { if (typeof value !== 'number' || !Number.isFinite(value)) fail(code); return value; };
const integer = (value, min, max, code) => { if (!Number.isInteger(value) || value < min || (max != null && value > max)) fail(code); return value; };
const known = (value, values, code) => { if (!values.includes(value)) fail(code); return value; };
const key = (value, code) => { string(value, 1, 48, code); if (!/^[A-Za-z][A-Za-z0-9_-]{0,47}$/u.test(value)) fail(code); return value; };
const uuid = (value, code) => { string(value, 36, 36, code); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu.test(value)) fail(code); return value; };
const hash = (value, code) => { string(value, 64, 64, code); if (!/^[a-f0-9]{64}$/u.test(value)) fail(code); return value; };
function exact(value, fields, code) { object(value, code); const keys = Object.keys(value); if (keys.length !== fields.length || keys.some(item => !fields.includes(item))) fail(`${code}_UNKNOWN_OR_MISSING_FIELD`); }
function exactWithOptional(value, fields, optionalFields, code) { object(value, code); const keys = Object.keys(value); if (keys.some(item => !fields.includes(item) && !optionalFields.includes(item)) || fields.some(item => !has(value, item))) fail(`${code}_UNKNOWN_OR_MISSING_FIELD`); }
function distinct(values, code) { if (new Set(values).size !== values.length) fail(code); }
function iso(value, nullable, code) { if (nullable && value === null) return; string(value, 20, 64, code); if (Number.isNaN(Date.parse(value))) fail(code); }
function jsonPointer(value, nullable, code) { if (nullable && value === null) return; string(value, 1, 1000, code); if (!value.startsWith('/')) fail(code); }
function forbiddenProposalFields(value) {
    const forbidden = new Set(['owner', 'ownerKey', 'canonicalId', 'allowWrite', 'approved', 'approval', 'confirmationToken', 'receipt', 'receiptId', 'operationId', 'verified', 'executionSucceeded', 'businessWritePolicy']);
    if (Array.isArray(value)) value.forEach(forbiddenProposalFields);
    else if (value && typeof value === 'object') for (const [name, child] of Object.entries(value)) { if (forbidden.has(name)) fail('PROPOSAL_PRIVILEGE_FIELD'); forbiddenProposalFields(child); }
}
function validateSourceSpan(span, context = {}) {
    exact(span, ['messageRef', 'start', 'end', 'text'], 'SOURCE_SPAN');
    string(span.messageRef, 1, 100, 'SOURCE_SPAN_MESSAGE_REF'); integer(span.start, 0, null, 'SOURCE_SPAN_START'); integer(span.end, 1, null, 'SOURCE_SPAN_END');
    if (span.end <= span.start) fail('SOURCE_SPAN_RANGE'); string(span.text, 1, 2000, 'SOURCE_SPAN_TEXT');
    const messages = context.sourceMessages;
    const source = messages instanceof Map ? messages.get(span.messageRef) : messages?.[span.messageRef];
    if (source !== undefined && (typeof source !== 'string' || source.slice(span.start, span.end) !== span.text)) fail('SOURCE_SPAN_TEXT_MISMATCH');
    return source !== undefined ? { structural: true, verified: true } : { structural: true, verified: false };
}
function validateQuantityInput(input, context) { exact(input, ['value', 'unit', 'sources'], 'QUANTITY'); finite(input.value, 'QUANTITY_VALUE'); known(input.unit, C.QuantityUnitsV1, 'QUANTITY_UNIT'); array(input.sources, 1, 8, 'QUANTITY_SOURCES').forEach(item => validateSourceSpan(item, context)); return true; }
function validateProposedOverride(value, context) { exact(value, ['field', 'value', 'unit', 'sources'], 'PROPOSED_OVERRIDE'); known(value.field, C.OverrideFieldsV1, 'PROPOSED_OVERRIDE_FIELD'); if (!['boolean', 'number', 'string'].includes(typeof value.value) || (typeof value.value === 'number' && !Number.isFinite(value.value))) fail('PROPOSED_OVERRIDE_VALUE'); if (value.unit !== null) string(value.unit, 1, 32, 'PROPOSED_OVERRIDE_UNIT'); array(value.sources, 1, 8, 'PROPOSED_OVERRIDE_SOURCES').forEach(item => validateSourceSpan(item, context)); return true; }
function validateTaskProposalV1(proposal, context = {}) {
    forbiddenProposalFields(proposal); exact(proposal, ['version', 'goalSummary', 'subjects', 'scenarios', 'goals', 'unparsedSpans'], 'TASK_PROPOSAL');
    if (proposal.version !== 1) fail('TASK_PROPOSAL_VERSION'); string(proposal.goalSummary, 1, 2000, 'TASK_PROPOSAL_SUMMARY');
    const subjects = array(proposal.subjects, 0, 12, 'TASK_PROPOSAL_SUBJECTS'); const subjectKeys = subjects.map(item => { exact(item, ['subjectKey', 'mention', 'typeHints', 'sources'], 'PROPOSAL_SUBJECT'); key(item.subjectKey, 'PROPOSAL_SUBJECT_KEY'); string(item.mention, 1, 160, 'PROPOSAL_SUBJECT_MENTION'); array(item.typeHints, 0, 6, 'PROPOSAL_TYPE_HINTS').forEach(hint => known(hint, C.TypeHintsV1, 'PROPOSAL_TYPE_HINT')); distinct(item.typeHints, 'PROPOSAL_TYPE_HINT_DUPLICATE'); array(item.sources, 1, 8, 'PROPOSAL_SUBJECT_SOURCES').forEach(span => validateSourceSpan(span, context)); return item.subjectKey; }); distinct(subjectKeys, 'PROPOSAL_SUBJECT_DUPLICATE');
    const scenarios = array(proposal.scenarios, 0, 4, 'TASK_PROPOSAL_SCENARIOS'); const scenarioKeys = scenarios.map(item => { exact(item, ['scenarioKey', 'label', 'baseSubjectKey', 'overrides', 'sources'], 'PROPOSAL_SCENARIO'); key(item.scenarioKey, 'PROPOSAL_SCENARIO_KEY'); if (item.scenarioKey === 'base') fail('PROPOSAL_RESERVED_SCENARIO_KEY'); string(item.label, 1, 80, 'PROPOSAL_SCENARIO_LABEL'); if (!subjectKeys.includes(item.baseSubjectKey)) fail('PROPOSAL_SCENARIO_SUBJECT'); array(item.overrides, 0, 20, 'PROPOSAL_SCENARIO_OVERRIDES').forEach(override => validateProposedOverride(override, context)); array(item.sources, 1, 8, 'PROPOSAL_SCENARIO_SOURCES').forEach(span => validateSourceSpan(span, context)); return item.scenarioKey; }); distinct(scenarioKeys, 'PROPOSAL_SCENARIO_DUPLICATE');
    const goals = array(proposal.goals, 1, 8, 'TASK_PROPOSAL_GOALS'); const goalKeys = goals.map(item => { exact(item, ['goalKey', 'kind', 'description', 'subjectKeys', 'scenarioKeys', 'dependsOn', 'requestedBasis', 'sources', 'quantity', 'unitPrice'], 'PROPOSAL_GOAL'); key(item.goalKey, 'PROPOSAL_GOAL_KEY'); known(item.kind, C.GoalKindV2, 'PROPOSAL_GOAL_KIND'); string(item.description, 1, 500, 'PROPOSAL_GOAL_DESCRIPTION'); for (const subjectKey of array(item.subjectKeys, 0, 8, 'PROPOSAL_GOAL_SUBJECTS')) if (!subjectKeys.includes(subjectKey)) fail('PROPOSAL_GOAL_SUBJECT_REF'); for (const scenarioKey of array(item.scenarioKeys, 0, 4, 'PROPOSAL_GOAL_SCENARIOS')) if (!scenarioKeys.includes(scenarioKey)) fail('PROPOSAL_GOAL_SCENARIO_REF'); array(item.dependsOn, 0, 8, 'PROPOSAL_GOAL_DEPENDS'); known(item.requestedBasis, ['CURRENT', 'SAVED', 'HYPOTHETICAL', 'UNKNOWN'], 'PROPOSAL_GOAL_BASIS'); array(item.sources, 1, 8, 'PROPOSAL_GOAL_SOURCES').forEach(span => validateSourceSpan(span, context)); if (item.quantity !== null) validateQuantityInput(item.quantity, context); if (item.unitPrice !== null) validateQuantityInput(item.unitPrice, context); return item.goalKey; }); distinct(goalKeys, 'PROPOSAL_GOAL_DUPLICATE');
    for (const goal of goals) for (const dependency of goal.dependsOn) if (!goalKeys.includes(dependency) || dependency === goal.goalKey) fail('PROPOSAL_GOAL_DEPENDENCY');
    const graph = new Map(goals.map(goal => [goal.goalKey, goal.dependsOn])); const visiting = new Set(), visited = new Set(); function visit(id) { if (visiting.has(id)) fail('PROPOSAL_GOAL_CYCLE'); if (!visited.has(id)) { visiting.add(id); graph.get(id).forEach(visit); visiting.delete(id); visited.add(id); } } goalKeys.forEach(visit);
    array(proposal.unparsedSpans, 0, 12, 'PROPOSAL_UNPARSED_SPANS').forEach(span => validateSourceSpan(span, context)); return true;
}
function validateCanonicalEntity(entity) { exact(entity, ['entityType', 'entityId', 'displayName', 'updatedAt', 'recordHash', 'schemeCode'], 'CANONICAL_ENTITY'); known(entity.entityType, C.EntityTypeV1, 'ENTITY_TYPE'); if (!/^[1-9][0-9]*$/u.test(string(entity.entityId, 1, 32, 'ENTITY_ID'))) fail('ENTITY_ID'); string(entity.displayName, 1, 240, 'ENTITY_NAME'); iso(entity.updatedAt, true, 'ENTITY_UPDATED_AT'); if (entity.recordHash !== null) hash(entity.recordHash, 'ENTITY_RECORD_HASH'); nullableString(entity.schemeCode, 1, 120, 'ENTITY_SCHEME_CODE'); return true; }
function sameEntity(left, right) { return left.entityType === right.entityType && left.entityId === right.entityId && left.displayName === right.displayName && left.updatedAt === right.updatedAt && left.recordHash === right.recordHash && left.schemeCode === right.schemeCode; }
function validateSubjectBinding(binding, trustedReceiptsById = new Map()) { exact(binding, ['subjectKey', 'mention', 'resolution', 'selected', 'candidates', 'candidateSetComplete', 'selectionBasis', 'receiptIds'], 'SUBJECT_BINDING'); key(binding.subjectKey, 'SUBJECT_BINDING_KEY'); string(binding.mention, 1, 160, 'SUBJECT_BINDING_MENTION'); known(binding.resolution, C.SubjectResolutionV2, 'SUBJECT_BINDING_RESOLUTION'); if (binding.selected !== null) validateCanonicalEntity(binding.selected); array(binding.candidates, 0, 20, 'SUBJECT_BINDING_CANDIDATES').forEach(validateCanonicalEntity); if (typeof binding.candidateSetComplete !== 'boolean') fail('SUBJECT_BINDING_COMPLETE'); known(binding.selectionBasis, C.SelectionBasisV2, 'SUBJECT_BINDING_BASIS'); array(binding.receiptIds, 0, 20, 'SUBJECT_BINDING_RECEIPTS').forEach(id => { uuid(id, 'SUBJECT_BINDING_RECEIPT'); if (trustedReceiptsById.size && !trustedReceiptsById.has(id)) fail('SUBJECT_BINDING_UNTRUSTED_RECEIPT'); });
    const selectedInCandidates = binding.selected && binding.candidates.some(item => sameEntity(item, binding.selected));
    if (binding.resolution === 'UNIQUE' && (!binding.candidateSetComplete || binding.candidates.length !== 1 || !selectedInCandidates || !['EXPLICIT_ID', 'EXACT', 'APPROVED_ALIAS'].includes(binding.selectionBasis))) fail('SUBJECT_UNIQUE_INVARIANT');
    if (binding.resolution === 'MULTIPLE' && (binding.selected !== null || binding.candidates.length < 2 || binding.selectionBasis !== 'NONE')) fail('SUBJECT_MULTIPLE_INVARIANT');
    if (binding.resolution === 'SELECTED' && (!selectedInCandidates || !['USER_CHOICE', 'FORMAL_DEFAULT', 'BASELINE_INHERITANCE'].includes(binding.selectionBasis) || !binding.receiptIds.length)) fail('SUBJECT_SELECTED_INVARIANT');
    if (binding.resolution === 'NOT_FOUND' && (binding.selected !== null || binding.candidates.length !== 0 || !binding.candidateSetComplete)) fail('SUBJECT_NOT_FOUND_INVARIANT');
    return true;
}
function validateArgumentSource(source, context = {}) {
    exactWithOptional(source, ['fieldPath', 'kind', 'sourceRef', 'pointer', 'span'], ['sourceVersionHash', 'rawValue', 'normalizedValue', 'transform'], 'ARGUMENT_SOURCE');
    jsonPointer(source.fieldPath, false, 'ARGUMENT_SOURCE_FIELD_PATH'); known(source.kind, C.ArgumentSourceKindV1, 'ARGUMENT_SOURCE_KIND'); string(source.sourceRef, 1, 160, 'ARGUMENT_SOURCE_REF');
    const hasEvidenceMetadata = ['sourceVersionHash', 'rawValue', 'normalizedValue', 'transform'].some(key => has(source, key));
    if (source.kind === 'USER_SPAN') { if (source.pointer !== null || source.span === null || source.sourceRef !== source.span.messageRef || hasEvidenceMetadata) fail('ARGUMENT_SOURCE_USER_SPAN'); validateSourceSpan(source.span, context); return true; }
    if (source.span !== null) fail('ARGUMENT_SOURCE_SPAN_FORBIDDEN');
    if (source.kind === 'FORMAL_RECEIPT') { if (hasEvidenceMetadata) fail('ARGUMENT_SOURCE_RECEIPT_METADATA'); jsonPointer(source.pointer, false, 'ARGUMENT_SOURCE_RECEIPT_POINTER'); return true; }
    if (source.kind !== 'SOURCE_EVIDENCE') { if (hasEvidenceMetadata || source.pointer !== null) fail('ARGUMENT_SOURCE_POINTER_FORBIDDEN'); return true; }
    if (source.pointer !== null || !has(source, 'sourceVersionHash') || !has(source, 'rawValue') || !has(source, 'normalizedValue') || !has(source, 'transform')) fail('SOURCE_EVIDENCE_SOURCE_SHAPE');
    hash(source.sourceVersionHash, 'SOURCE_EVIDENCE_VERSION_HASH');
    if (!['string', 'number', 'boolean'].includes(typeof source.rawValue) || !['string', 'number', 'boolean'].includes(typeof source.normalizedValue)) fail('SOURCE_EVIDENCE_VALUE');
    exact(source.transform, ['type', 'fromUnit', 'toUnit'], 'SOURCE_EVIDENCE_TRANSFORM');
    known(source.transform.type, ['IDENTITY', 'UNIT_CONVERSION'], 'SOURCE_EVIDENCE_TRANSFORM_TYPE');
    if (source.transform.fromUnit !== null) string(source.transform.fromUnit, 1, 16, 'SOURCE_EVIDENCE_FROM_UNIT');
    if (source.transform.toUnit !== null) string(source.transform.toUnit, 1, 16, 'SOURCE_EVIDENCE_TO_UNIT');
    const records = context.trustedSourceEvidenceById instanceof Map ? context.trustedSourceEvidenceById : new Map(Object.entries(context.trustedSourceEvidenceById || {}));
    const record = records.get(source.sourceRef);
    if (!record || record.taskId !== context.taskId || record.planRevision !== context.planRevision || record.sourceVersionHash !== source.sourceVersionHash) fail('SOURCE_EVIDENCE_UNTRUSTED');
    if (!String(record.excerpt).includes(String(source.rawValue))) fail('SOURCE_EVIDENCE_RAW_NOT_EVIDENCED');
    const conversion = source.transform;
    const validIdentity = conversion.type === 'IDENTITY' && conversion.fromUnit === null && conversion.toUnit === null && source.rawValue === source.normalizedValue;
    // Source evidence preserves the literal source token.  A bare number has no
    // unit evidence, so only an exact `500cm`-style source can become metres.
    const cmMatch = typeof source.rawValue === 'string' && /^([0-9]+(?:\.[0-9]+)?)cm$/u.exec(source.rawValue);
    const validCmToM = conversion.type === 'UNIT_CONVERSION' && conversion.fromUnit === 'cm' && conversion.toUnit === 'm' && cmMatch && typeof source.normalizedValue === 'number' && Number.isFinite(source.normalizedValue) && source.normalizedValue === Number(cmMatch[1]) / 100;
    if (!validIdentity && !validCmToM) fail('SOURCE_EVIDENCE_NONDETERMINISTIC_TRANSFORM');
    return true;
}
function validateScenarioOverridesV1(value) { object(value, 'SCENARIO_OVERRIDES'); const allowed = ['hasFloat', 'floatWire', 'floatAccessoryType', 'hasCable', 'cableLength', 'cableWire', 'cableAccessoryType', 'coilId', 'coilSheets', 'customBarrelLength', 'packingParts', 'surfaceTreatmentMode', 'surfaceTreatmentCost']; if (Object.keys(value).some(field => !allowed.includes(field))) fail('SCENARIO_OVERRIDES_UNKNOWN_FIELD'); if (has(value, 'hasFloat') && typeof value.hasFloat !== 'boolean') fail('OVERRIDE_HAS_FLOAT'); if (has(value, 'hasCable') && typeof value.hasCable !== 'boolean') fail('OVERRIDE_HAS_CABLE'); for (const field of ['floatWire', 'cableWire']) if (has(value, field)) string(value[field], 1, 40, 'OVERRIDE_STRING'); for (const field of ['floatAccessoryType', 'cableAccessoryType']) if (has(value, field)) known(value[field], ['standard', 'xinjie'], 'OVERRIDE_ACCESSORY'); if (has(value, 'cableLength')) finite(value.cableLength, 'OVERRIDE_CABLE_LENGTH'); if (has(value, 'coilId')) integer(value.coilId, 1, null, 'OVERRIDE_COIL_ID'); if (has(value, 'coilSheets')) integer(value.coilSheets, 1, null, 'OVERRIDE_COIL_SHEETS'); if (has(value, 'customBarrelLength') && !(finite(value.customBarrelLength, 'OVERRIDE_BARREL_LENGTH') > 0)) fail('OVERRIDE_BARREL_LENGTH'); if (has(value, 'surfaceTreatmentMode')) known(value.surfaceTreatmentMode, ['none', 'painting', 'electrophoresis', 'electrophoresis_powder_coating', 'powder_coating', 'custom'], 'OVERRIDE_SURFACE_MODE'); if (has(value, 'surfaceTreatmentCost') && finite(value.surfaceTreatmentCost, 'OVERRIDE_SURFACE_COST') < 0) fail('OVERRIDE_SURFACE_COST'); if (has(value, 'packingParts')) array(value.packingParts, 0, 12, 'OVERRIDE_PACKING').forEach(part => { exact(part, ['partId', 'model', 'supplier', 'qty', 'packingRole'], 'PACKING_PART'); integer(part.partId, 1, null, 'PACKING_PART_ID'); string(part.model, 1, 160, 'PACKING_MODEL'); string(part.supplier, 1, 160, 'PACKING_SUPPLIER'); finite(part.qty, 'PACKING_QTY'); known(part.packingRole, ['container', 'pearlCotton', 'foam', 'fixed'], 'PACKING_ROLE'); }); return true; }
function validateFactKey(keyValue) { exact(keyValue, ['entityType', 'entityId', 'predicate', 'temporalScope', 'scenarioKey', 'qualifiers'], 'FACT_KEY'); known(keyValue.entityType, C.FactEntityTypeV1, 'FACT_ENTITY_TYPE'); if (keyValue.entityId !== null && !/^[1-9][0-9]*$/u.test(string(keyValue.entityId, 1, 32, 'FACT_ENTITY_ID'))) fail('FACT_ENTITY_ID'); string(keyValue.predicate, 1, 100, 'FACT_PREDICATE'); known(keyValue.temporalScope, C.TemporalScopeV1, 'FACT_TEMPORAL'); if (keyValue.temporalScope === 'SCENARIO' ? keyValue.scenarioKey === null : keyValue.scenarioKey !== null) fail('FACT_SCENARIO_SCOPE'); if (keyValue.scenarioKey !== null) key(keyValue.scenarioKey, 'FACT_SCENARIO_KEY'); exact(keyValue.qualifiers, ['basis', 'unit', 'currency', 'snapshotVersion', 'queryScopeHash'], 'FACT_QUALIFIERS'); string(keyValue.qualifiers.basis, 1, 100, 'FACT_BASIS'); string(keyValue.qualifiers.unit, 1, 32, 'FACT_UNIT'); nullableString(keyValue.qualifiers.currency, 1, 16, 'FACT_CURRENCY'); nullableString(keyValue.qualifiers.snapshotVersion, 1, 160, 'FACT_SNAPSHOT_VERSION'); if (keyValue.qualifiers.queryScopeHash !== null) hash(keyValue.qualifiers.queryScopeHash, 'FACT_SCOPE_HASH'); if (keyValue.entityType === 'global' ? keyValue.entityId !== null : keyValue.entityId === null && keyValue.qualifiers.queryScopeHash === null) fail('FACT_ENTITY_SCOPE'); return true; }
function factKeyIdentity(keyValue) { return C.canonicalJson({ entityType: keyValue.entityType, entityId: keyValue.entityId, predicate: keyValue.predicate, temporalScope: keyValue.temporalScope, scenarioKey: keyValue.scenarioKey, qualifiers: keyValue.qualifiers }); }
function pointerExists(value, pointer) { let current = value; for (const token of pointer.slice(1).split('/').map(item => item.replace(/~1/g, '/u').replace(/~0/g, '~u'))) { if (!current || typeof current !== 'object' || !has(current, token)) return false; current = current[token]; } return true; }
function readPointer(value, pointer) { let current = value; for (const token of pointer.slice(1).split('/').map(item => item.replace(/~1/g, '/u').replace(/~0/g, '~u'))) { if (!current || typeof current !== 'object' || !has(current, token)) return undefined; current = current[token]; } return current; }
function validateFactRecordV1(fact, context = {}) { exact(fact, ['version', 'factId', 'key', 'evidenceState', 'value', 'receiptId', 'resultPointer', 'observedAt', 'sourceUpdatedAt', 'sourceHash', 'complete', 'supersedesFactId', 'planRevision', 'readSetId'], 'FACT_RECORD'); if (fact.version !== 1) fail('FACT_VERSION'); uuid(fact.factId, 'FACT_ID'); validateFactKey(fact.key); known(fact.evidenceState, C.EvidenceStateV1, 'FACT_EVIDENCE'); uuid(fact.receiptId, 'FACT_RECEIPT'); jsonPointer(fact.resultPointer, false, 'FACT_RESULT_POINTER'); iso(fact.observedAt, false, 'FACT_OBSERVED_AT'); iso(fact.sourceUpdatedAt, true, 'FACT_SOURCE_UPDATED_AT'); hash(fact.sourceHash, 'FACT_SOURCE_HASH'); if (typeof fact.complete !== 'boolean') fail('FACT_COMPLETE'); if (fact.supersedesFactId !== null) uuid(fact.supersedesFactId, 'FACT_SUPERSEDES'); integer(fact.planRevision, 1, null, 'FACT_PLAN_REVISION'); if (fact.readSetId !== null) uuid(fact.readSetId, 'FACT_READ_SET'); if (fact.evidenceState === 'VERIFIED_NEGATIVE' && (!fact.complete || fact.key.qualifiers.queryScopeHash === null)) fail('FACT_NEGATIVE_SCOPE'); const receipt = context.trustedReceiptsById instanceof Map ? context.trustedReceiptsById.get(fact.receiptId) : context.trustedReceiptsById?.[fact.receiptId]; if (!receipt) fail('FACT_UNTRUSTED_RECEIPT'); if (receipt.taskId !== context.taskId || receipt.planRevision !== fact.planRevision || receipt.sourceHash !== fact.sourceHash) fail('FACT_RECEIPT_MISMATCH'); if (!pointerExists(receipt.result, fact.resultPointer)) fail('FACT_RESULT_POINTER_UNTRUSTED'); if (C.canonicalJson(readPointer(receipt.result, fact.resultPointer)) !== C.canonicalJson(fact.value)) fail('FACT_RESULT_VALUE_MISMATCH'); if (fact.supersedesFactId !== null) { const old = context.factsById instanceof Map ? context.factsById.get(fact.supersedesFactId) : context.factsById?.[fact.supersedesFactId]; if (!old || old.taskId !== context.taskId || old.planRevision >= fact.planRevision || factKeyIdentity(old.key) !== factKeyIdentity(fact.key)) fail('FACT_SUPERSEDE_INVARIANT'); } return true; }
function validateFactRequirement(requirement) { exact(requirement, ['requirementKey', 'predicate', 'subjectKey', 'scenarioKey', 'temporalScope', 'basis', 'requireComplete', 'unit', 'currency'], 'FACT_REQUIREMENT'); string(requirement.requirementKey, 1, 100, 'REQUIREMENT_KEY'); string(requirement.predicate, 1, 100, 'REQUIREMENT_PREDICATE'); if (requirement.subjectKey !== null) key(requirement.subjectKey, 'REQUIREMENT_SUBJECT'); if (requirement.scenarioKey !== null) key(requirement.scenarioKey, 'REQUIREMENT_SCENARIO'); known(requirement.temporalScope, C.TemporalScopeV1, 'REQUIREMENT_TEMPORAL'); nullableString(requirement.basis, 1, 100, 'REQUIREMENT_BASIS'); if (typeof requirement.requireComplete !== 'boolean') fail('REQUIREMENT_COMPLETE'); nullableString(requirement.unit, 1, 32, 'REQUIREMENT_UNIT'); nullableString(requirement.currency, 1, 16, 'REQUIREMENT_CURRENCY'); return true; }
function factSatisfiesRequirement(requirement, fact, subjectBindings = []) { validateFactRequirement(requirement); if (!fact || fact.evidenceState !== 'VERIFIED_POSITIVE' && fact.evidenceState !== 'VERIFIED_NEGATIVE') return false; const k = fact.key; if (k.predicate !== requirement.predicate || k.temporalScope !== requirement.temporalScope || k.scenarioKey !== requirement.scenarioKey || (requirement.basis !== null && k.qualifiers.basis !== requirement.basis) || (requirement.unit !== null && k.qualifiers.unit !== requirement.unit) || (requirement.currency !== null && k.qualifiers.currency !== requirement.currency) || (requirement.requireComplete && !fact.complete)) return false; if (requirement.subjectKey === null) return k.entityType === 'global' && k.entityId === null; const binding = subjectBindings.find(item => item.subjectKey === requirement.subjectKey); return Boolean(binding?.selected && binding.selected.entityType === k.entityType && binding.selected.entityId === k.entityId); }
function validateGoalState(goal, context) { exactWithOptional(goal, ['goalKey', 'kind', 'description', 'subjectKeys', 'scenarioKeys', 'dependsOn', 'state', 'factIds', 'blockers', 'requirements'], ['sourceEvidenceIds'], 'GOAL_STATE'); key(goal.goalKey, 'GOAL_KEY'); known(goal.kind, C.GoalKindV2, 'GOAL_KIND'); string(goal.description, 1, 500, 'GOAL_DESCRIPTION'); array(goal.subjectKeys, 0, 8, 'GOAL_SUBJECTS'); array(goal.scenarioKeys, 0, 4, 'GOAL_SCENARIOS'); array(goal.dependsOn, 0, 8, 'GOAL_DEPENDS'); known(goal.state, C.GoalStateV2, 'GOAL_STATE'); array(goal.factIds, 0, 64, 'GOAL_FACTS').forEach(id => uuid(id, 'GOAL_FACT')); const sourceEvidenceIds = goal.sourceEvidenceIds === undefined ? [] : array(goal.sourceEvidenceIds, 0, 32, 'GOAL_SOURCE_EVIDENCE'); sourceEvidenceIds.forEach(id => { uuid(id, 'GOAL_SOURCE_EVIDENCE_ID'); if (!context.sourceEvidenceById?.has(id)) fail('GOAL_SOURCE_EVIDENCE_REF'); }); const blockers = array(goal.blockers, 0, 12, 'GOAL_BLOCKERS'); blockers.forEach(item => { exact(item, ['code', 'message', 'questionId'], 'GOAL_BLOCKER'); string(item.code, 1, 100, 'GOAL_BLOCKER_CODE'); string(item.message, 1, 1000, 'GOAL_BLOCKER_MESSAGE'); if (item.questionId !== null) uuid(item.questionId, 'GOAL_BLOCKER_QUESTION'); }); const requirements = array(goal.requirements, 0, 24, 'GOAL_REQUIREMENTS'); requirements.forEach(validateFactRequirement); if (goal.state === 'UNSUPPORTED' && !blockers.length) fail('GOAL_UNSUPPORTED_BLOCKER'); if (goal.state === 'VERIFIED') { if (!requirements.length && !sourceEvidenceIds.length) fail('GOAL_VERIFIED_REQUIREMENTS'); const facts = goal.factIds.map(id => context.factsById.get(id)).filter(Boolean); if (!requirements.every(requirement => facts.some(fact => factSatisfiesRequirement(requirement, fact, context.subjects)))) fail('GOAL_VERIFIED_UNSATISFIED'); } return true; }
function validateTaskStep(step, context) { exact(step, ['stepId', 'goalKeys', 'toolName', 'capabilityId', 'access', 'arguments', 'argumentSources', 'argsHash', 'state', 'attempt', 'startedAt', 'finishedAt', 'receiptId', 'operationId', 'errorCode'], 'TASK_STEP'); uuid(step.stepId, 'STEP_ID'); array(step.goalKeys, 1, 8, 'STEP_GOALS').forEach(goalKey => { if (!context.goalKeys.has(goalKey)) fail('STEP_GOAL_REF'); }); string(step.toolName, 1, 100, 'STEP_TOOL'); string(step.capabilityId, 1, 160, 'STEP_CAPABILITY'); known(step.access, C.StepAccessV1, 'STEP_ACCESS'); object(step.arguments, 'STEP_ARGUMENTS'); const sources = array(step.argumentSources, 0, 80, 'STEP_ARGUMENT_SOURCES'); sources.forEach(source => validateArgumentSource(source, context)); if (Object.keys(step.arguments).length && !sources.length) fail('STEP_ARGUMENT_SOURCES_REQUIRED'); if (C.stableHash(step.arguments) !== step.argsHash) fail('STEP_ARGS_HASH'); hash(step.argsHash, 'STEP_ARGS_HASH'); known(step.state, C.StepStateV1, 'STEP_STATE'); integer(step.attempt, 1, 10, 'STEP_ATTEMPT'); iso(step.startedAt, true, 'STEP_STARTED'); iso(step.finishedAt, true, 'STEP_FINISHED'); for (const field of ['receiptId', 'operationId', 'errorCode']) if (step[field] !== null) string(step[field], 1, 160, `STEP_${field}`); if (context.businessWritePolicy === 'FORBIDDEN' && step.access === 'COMMAND') fail('STEP_COMMAND_FORBIDDEN'); return true; }
function validateTaskEnvelopeV2(task, context = {}) {
    exactWithOptional(task, ['version', 'taskId', 'parentTaskId', 'ownerKey', 'conversationId', 'requestId', 'revision', 'planRevision', 'state', 'answerOwner', 'executionMode', 'userGoal', 'inputHash', 'createdAt', 'updatedAt', 'constraints', 'subjects', 'goals', 'scenarios', 'steps', 'facts', 'questions', 'approvalOperationIds', 'resultSummary', 'budgetUsage'], ['sourceEvidence', 'sourceConflicts', 'sourceConfigComparisons'], 'TASK_ENVELOPE'); if (task.version !== 2) fail('TASK_VERSION'); uuid(task.taskId, 'TASK_ID'); if (task.parentTaskId !== null) uuid(task.parentTaskId, 'TASK_PARENT'); string(task.ownerKey, 1, 80, 'TASK_OWNER'); if (task.conversationId !== null) string(task.conversationId, 1, 160, 'TASK_CONVERSATION'); string(task.requestId, 1, 160, 'TASK_REQUEST'); integer(task.revision, 1, null, 'TASK_REVISION'); integer(task.planRevision, 1, null, 'TASK_PLAN_REVISION'); known(task.state, C.TaskStateV2, 'TASK_STATE'); if (task.answerOwner !== 'TASK_V2') fail('TASK_ANSWER_OWNER'); known(task.executionMode, C.TaskExecutionModeV1, 'TASK_EXECUTION_MODE'); string(task.userGoal, 1, 2000, 'TASK_USER_GOAL'); hash(task.inputHash, 'TASK_INPUT_HASH'); iso(task.createdAt, false, 'TASK_CREATED'); iso(task.updatedAt, false, 'TASK_UPDATED'); exact(task.constraints, ['businessWritePolicy', 'maxModelCalls', 'maxToolCalls', 'maxToolResultBytes', 'maxTaskStateBytes', 'deadlineAt', 'maxApiCalls', 'maxActiveMs'], 'TASK_CONSTRAINTS'); known(task.constraints.businessWritePolicy, C.BusinessWritePolicyV1, 'TASK_WRITE_POLICY'); integer(task.constraints.maxModelCalls, 1, 7, 'TASK_MODEL_BUDGET'); integer(task.constraints.maxToolCalls, 1, 10, 'TASK_TOOL_BUDGET'); if (task.constraints.maxToolResultBytes !== 98304 || task.constraints.maxTaskStateBytes !== 262144) fail('TASK_FIXED_LIMIT'); iso(task.constraints.deadlineAt, true, 'TASK_DEADLINE'); integer(task.constraints.maxApiCalls, 1, 128, 'TASK_API_BUDGET'); integer(task.constraints.maxActiveMs, 10000, 900000, 'TASK_ACTIVE_BUDGET');
    const trustedReceiptsById = context.trustedReceiptsById || new Map(); const subjects = array(task.subjects, 0, 12, 'TASK_SUBJECTS'); subjects.forEach(subject => validateSubjectBinding(subject, trustedReceiptsById)); const subjectKeys = subjects.map(item => item.subjectKey); distinct(subjectKeys, 'TASK_SUBJECT_DUPLICATE'); const scenarios = array(task.scenarios, 0, 4, 'TASK_SCENARIOS'); const scenarioKeys = scenarios.map(item => { exact(item, ['scenarioKey', 'label', 'baseSubjectKey', 'basis', 'priceContext', 'overrides', 'readSetId'], 'TASK_SCENARIO'); key(item.scenarioKey, 'TASK_SCENARIO_KEY'); string(item.label, 1, 80, 'TASK_SCENARIO_LABEL'); if (!subjectKeys.includes(item.baseSubjectKey)) fail('TASK_SCENARIO_SUBJECT'); known(item.basis, C.ScenarioBasisV1, 'TASK_SCENARIO_BASIS'); known(item.priceContext, C.ScenarioPriceContextV1, 'TASK_SCENARIO_PRICE_CONTEXT'); validateScenarioOverridesV1(item.overrides); if (item.readSetId !== null) uuid(item.readSetId, 'TASK_SCENARIO_READ_SET'); return item.scenarioKey; }); distinct(scenarioKeys, 'TASK_SCENARIO_DUPLICATE');
    const rawFacts = array(task.facts, 0, 64, 'TASK_FACTS'); const factsById = new Map(rawFacts.map(item => [item.factId, item])); distinct([...factsById.keys()], 'TASK_FACT_DUPLICATE'); rawFacts.forEach(fact => validateFactRecordV1(fact, { ...context, taskId: task.taskId, trustedReceiptsById, factsById })); const rawSourceEvidence = task.sourceEvidence === undefined ? [] : array(task.sourceEvidence, 0, 32, 'TASK_SOURCE_EVIDENCE'); rawSourceEvidence.forEach(validateSourceEvidenceRecordV1); const sourceEvidenceById = new Map(rawSourceEvidence.map(item => [item.evidenceId, item])); distinct([...sourceEvidenceById.keys()], 'TASK_SOURCE_EVIDENCE_DUPLICATE'); if (rawSourceEvidence.some(item => item.taskId !== task.taskId || item.planRevision > task.planRevision)) fail('TASK_SOURCE_EVIDENCE_REVISION'); const rawSourceConflicts = task.sourceConflicts === undefined ? [] : array(task.sourceConflicts, 0, 24, 'TASK_SOURCE_CONFLICTS'); rawSourceConflicts.forEach(item => validateSourceConflictV1(item, sourceEvidenceById)); const conflictIds = rawSourceConflicts.map(item => item.conflictId); distinct(conflictIds, 'TASK_SOURCE_CONFLICT_DUPLICATE'); const rawSourceConfigComparisons = task.sourceConfigComparisons === undefined ? [] : array(task.sourceConfigComparisons, 0, 32, 'TASK_SOURCE_CONFIG_COMPARISONS'); rawSourceConfigComparisons.forEach(item => validateSourceConfigComparisonV1(item, sourceEvidenceById)); const goals = array(task.goals, 1, 8, 'TASK_GOALS'); const goalKeys = goals.map(item => item.goalKey); distinct(goalKeys, 'TASK_GOAL_DUPLICATE'); const goalSet = new Set(goalKeys); goals.forEach(goal => { validateGoalState(goal, { factsById, subjects, sourceEvidenceById }); for (const subjectKey of goal.subjectKeys) if (!subjectKeys.includes(subjectKey)) fail('GOAL_SUBJECT_REF'); for (const scenarioKey of goal.scenarioKeys) if (!scenarioKeys.includes(scenarioKey)) fail('GOAL_SCENARIO_REF'); for (const dependency of goal.dependsOn) if (!goalSet.has(dependency) || dependency === goal.goalKey) fail('GOAL_DEPENDENCY'); }); const graph = new Map(goals.map(goal => [goal.goalKey, goal.dependsOn])); const visiting = new Set(), visited = new Set(); function visit(id) { if (visiting.has(id)) fail('GOAL_CYCLE'); if (!visited.has(id)) { visiting.add(id); graph.get(id).forEach(visit); visiting.delete(id); visited.add(id); } } goalKeys.forEach(visit);
    array(task.steps, 0, 10, 'TASK_STEPS').forEach(step => validateTaskStep(step, { ...context, trustedSourceEvidenceById: sourceEvidenceById, taskId: task.taskId, planRevision: task.planRevision, goalKeys: goalSet, businessWritePolicy: task.constraints.businessWritePolicy })); const questions = array(task.questions, 0, 12, 'TASK_QUESTIONS'); questions.forEach(question => { exact(question, ['questionId', 'planRevision', 'goalKeys', 'prompt', 'reasonCode', 'choices', 'candidateSetHash', 'expiresAt', 'answeredAt'], 'TASK_QUESTION'); uuid(question.questionId, 'QUESTION_ID'); integer(question.planRevision, 1, null, 'QUESTION_PLAN_REVISION'); array(question.goalKeys, 1, 8, 'QUESTION_GOALS').forEach(goalKey => { if (!goalSet.has(goalKey)) fail('QUESTION_GOAL_REF'); }); string(question.prompt, 1, 1000, 'QUESTION_PROMPT'); string(question.reasonCode, 1, 100, 'QUESTION_REASON'); array(question.choices, 0, 20, 'QUESTION_CHOICES').forEach(choice => { exact(choice, ['choiceId', 'label', 'entity'], 'QUESTION_CHOICE'); key(choice.choiceId, 'QUESTION_CHOICE_ID'); string(choice.label, 1, 240, 'QUESTION_CHOICE_LABEL'); validateCanonicalEntity(choice.entity); }); hash(question.candidateSetHash, 'QUESTION_CANDIDATE_HASH'); iso(question.expiresAt, false, 'QUESTION_EXPIRES'); iso(question.answeredAt, true, 'QUESTION_ANSWERED'); }); const questionIds = questions.map(item => item.questionId); distinct(questionIds, 'QUESTION_DUPLICATE'); array(task.approvalOperationIds, 0, 8, 'TASK_APPROVALS').forEach(id => uuid(id, 'TASK_APPROVAL')); if (task.constraints.businessWritePolicy === 'FORBIDDEN' && task.approvalOperationIds.length) fail('TASK_APPROVAL_FORBIDDEN'); if (task.resultSummary !== null) string(task.resultSummary, 1, 4000, 'TASK_RESULT_SUMMARY'); exact(task.budgetUsage, ['modelCalls', 'toolCalls', 'apiCalls', 'activeMs'], 'TASK_BUDGET_USAGE'); for (const field of ['modelCalls', 'toolCalls', 'apiCalls', 'activeMs']) integer(task.budgetUsage[field], 0, null, 'TASK_BUDGET_USAGE'); if (task.budgetUsage.modelCalls > task.constraints.maxModelCalls || task.budgetUsage.toolCalls > task.constraints.maxToolCalls || task.budgetUsage.apiCalls > task.constraints.maxApiCalls || task.budgetUsage.activeMs > task.constraints.maxActiveMs) fail('TASK_BUDGET_EXCEEDED'); if (task.state === 'SUCCEEDED' && !goals.every(goal => goal.state === 'VERIFIED')) fail('TASK_SUCCEEDED_GOALS'); if (Buffer.byteLength(JSON.stringify(task), 'utf8') > task.constraints.maxTaskStateBytes) fail('TASK_STATE_TOO_LARGE'); return true;
}
function validateTaskTransitionV2(previous, next, context = {}) { validateTaskEnvelopeV2(previous, context); validateTaskEnvelopeV2(next, context); if (previous.taskId !== next.taskId || next.revision !== previous.revision + 1) fail('TASK_TRANSITION_REVISION'); if (C.TERMINAL_TASK_STATES.includes(previous.state) || !C.TASK_TRANSITIONS_V2[previous.state].includes(next.state)) fail('TASK_TRANSITION_STATE'); const before = new Map(previous.scenarios.map(item => [item.scenarioKey, item])); for (const scenario of next.scenarios) if (before.has(scenario.scenarioKey) && C.canonicalJson(before.get(scenario.scenarioKey)) !== C.canonicalJson(scenario)) fail('TASK_SCENARIO_MUTATED'); const changedPlan = C.canonicalJson({ subjects: previous.subjects, goals: previous.goals, scenarios: previous.scenarios, questions: previous.questions }) !== C.canonicalJson({ subjects: next.subjects, goals: next.goals, scenarios: next.scenarios, questions: next.questions }); if (changedPlan ? next.planRevision <= previous.planRevision : next.planRevision !== previous.planRevision) fail('TASK_TRANSITION_PLAN_REVISION'); return true; }
module.exports = { AiTaskValidationError, factKeyIdentity, factSatisfiesRequirement, validateArgumentSource, validateCanonicalEntity, validateFactKey, validateFactRecordV1, validateFactRequirement, validateGoalState, validateProposedOverride, validateQuantityInput, validateScenarioOverridesV1, validateSourceSpan, validateSubjectBinding, validateTaskEnvelopeV2, validateTaskProposalV1, validateTaskStep, validateTaskTransitionV2 };
