const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'pump-owner-promotion-http-'));
process.env.NODE_ENV = 'test'; process.env.PUMP_TEST_DATABASE_PATH = path.join(directory, 'pump-{pid}.db'); process.env.JWT_SECRET = 'owner-promotion-http-secret';
const express = require('express'); const cookieParser = require('cookie-parser'); const jwt = require('jsonwebtoken'); const auth = require('../api/authMiddleware.cjs'); const router = require('../api/routes/recipes.cjs'); const { db, stopBackupScheduler } = require('../api/db.cjs');
const { createRecipeTechnicalMigrationDryRunService } = require('../api/services/recipeTechnicalMigrationDryRun.cjs'); const { createRecipeTechnicalMigrationBackfillService } = require('../api/services/recipeTechnicalMigrationBackfill.cjs'); const { createRecipeTechnicalProfileService } = require('../api/services/recipeTechnicalProfile.cjs');
const NOW='2026-09-28T00:00:00.000Z'; const COOKIE=`token=${jwt.sign({id:1,username:'promotion-http',role:'admin'},process.env.JWT_SECRET,{expiresIn:'5m'})}`; let server,baseUrl;
async function request(method,url,body){const response=await fetch(`${baseUrl}${url}`,{method,headers:{'content-type':'application/json',cookie:COOKIE},body:body===undefined?undefined:JSON.stringify(body)});return{response,payload:await response.json()};}
test.before(async()=>{const app=express();app.use(express.json());app.use(cookieParser());app.use('/api',auth);app.use('/api/recipes',router);server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));baseUrl=`http://127.0.0.1:${server.address().port}`;});
test.after(async()=>{stopBackupScheduler();server?.closeAllConnections?.();await new Promise(resolve=>server.close(resolve));if(db.open)db.close();fs.rmSync(directory,{recursive:true,force:true});});
test('HTTP preview and promotion preserve canonical values while adopting source-drifted authority',async()=>{
 const shell=Number(db.prepare(`INSERT INTO parts(model,category,remark,created_at,updated_at)VALUES('s','泵壳','{"isStainless":false}',?,?)`).run(NOW,NOW).lastInsertRowid);db.prepare(`INSERT INTO parts(model,category,created_at,updated_at)VALUES('轴承-6202','轴承',?,?),('轴承-6303','轴承',?,?)`).run(NOW,NOW,NOW,NOW);const template=Number(db.prepare(`INSERT INTO pump_shell_templates(shell_model,created_at,updated_at)VALUES('t',?,?)`).run(NOW,NOW).lastInsertRowid);db.prepare(`INSERT INTO catalog_template_shell_bindings(template_id,shell_part_id,created_at,updated_at)VALUES(?,?,?,?)`).run(template,shell,NOW,NOW);const payload={rotorDiameter:52,stackOffset:1,oilSealDiameter:20,impellerBoreDiameter:12,impellerSpan:24,impellerDepth:3,threadLength:14,threadDiameter:8,upperBearing:'202',lowerBearing:'6303',bearingSpan:80};const recipe=Number(db.prepare(`INSERT INTO recipes(name,template_id,coil_sheets,impeller_thickness,technical_data_json,created_at,updated_at)VALUES('r',?,160,3,?,?,?)`).run(template,JSON.stringify(payload),NOW,NOW).lastInsertRowid);
 const dry=createRecipeTechnicalMigrationDryRunService({db});const canonical=createRecipeTechnicalProfileService({db});const backfill=createRecipeTechnicalMigrationBackfillService({db,dryRunService:dry,canonicalProfileService:canonical});const bp=backfill.preview(recipe,{actorKey:'http',subject:'http'});backfill.apply(recipe,{confirmationToken:bp.confirmationToken,idempotencyKey:'owner-http-backfill-001'},{actorKey:'http',subject:'http',idempotencyKey:'owner-http-backfill-001'});db.prepare(`UPDATE recipes SET technical_data_json=? WHERE id=?`).run(JSON.stringify({...payload,rotorDiameter:99}),recipe);
 const preview=await request('POST',`/api/recipes/${recipe}/technical-profile/migration-owner-promotion-preview`,{decision:'ADOPT_CURRENT_CANONICAL'});assert.equal(preview.response.status,200);const apply=await request('POST',`/api/recipes/${recipe}/technical-profile/migration-owner-promote`,{confirmationToken:preview.payload.data.confirmationToken,idempotencyKey:'owner-http-promotion-001'});assert.equal(apply.response.status,200);assert.equal(apply.payload.data.technicalProfile.functional.rotorDiameter,52);assert.equal(apply.payload.data.migrationStateAfter,'ALREADY_CANONICAL');
});
