'use strict';

const IMPACT_ENFORCEMENT_FLAG = 'AI_BUSINESS_IMPACT_ENFORCEMENT_CANARY_ENABLED';
const IMPACT_ELIGIBILITY_VERSION = 1;
const IMPACT_EVIDENCE_BUNDLE_VERSION = 1;
const IMPACT_ANSWER_BOUNDARY_VERSION = 1;
const MAX_IMPACT_EVIDENCE_BUNDLE_BYTES = 16 * 1024;

const SUPPORTED_SLICES = Object.freeze([
    'IP-01_CONFIGURATION_CHANGE',
    'IP-02_RECIPE_SNAPSHOT_COMPARISON',
    'IP-03_INVENTORY_READINESS',
    'IP-04_TEMPLATE_RECIPES',
    'IP-05_PART_PRICE_RECIPES',
]);

const OBLIGATIONS = Object.freeze([
    'DISCLOSE_PROPOSED_NOT_ACTUAL',
    'DISCLOSE_CURRENT_RECIPE_AFFECTED',
    'DISCLOSE_COST_RECALCULATION_REQUIRED',
    'DISCLOSE_SAVED_ORDER_NOT_MUTATED',
    'DISCLOSE_SAVED_ORDER_REVIEW_REQUIRED',
    'DISCLOSE_VERIFIED_ORDER_DIFFERENCE',
    'DISCLOSE_READINESS_RECOMPUTE_REQUIRED',
    'DISCLOSE_AFFECTED_RECIPE_SET',
    'DISCLOSE_INCOMPLETE_IMPACT_SCOPE',
    'DISCLOSE_ENGINEERING_UNKNOWN',
    'DISCLOSE_QUOTATION_FRESHNESS_UNKNOWN',
    'DISCLOSE_REPORT_APPLICABILITY_UNKNOWN',
]);

const FORBIDDEN_CLAIMS = Object.freeze([
    'MUST_NOT_CLAIM_PROPOSED_CHANGE_OCCURRED',
    'MUST_NOT_CLAIM_SAVED_ORDER_CHANGED',
    'MUST_NOT_CLAIM_RECIPE_COST_ALREADY_CHANGED',
    'MUST_NOT_CLAIM_QUOTATION_STALE',
    'MUST_NOT_CLAIM_QUOTATION_CURRENT',
    'MUST_NOT_CLAIM_TEST_REPORT_VALID',
    'MUST_NOT_CLAIM_TEST_REPORT_INVALID',
    'MUST_NOT_PREDICT_ENGINEERING_NUMBER',
    'MUST_NOT_PREDICT_ENGINEERING_DIRECTION_AS_FACTORY_FACT',
]);

module.exports = { IMPACT_ENFORCEMENT_FLAG, IMPACT_ELIGIBILITY_VERSION,
    IMPACT_EVIDENCE_BUNDLE_VERSION, IMPACT_ANSWER_BOUNDARY_VERSION,
    MAX_IMPACT_EVIDENCE_BUNDLE_BYTES, SUPPORTED_SLICES, OBLIGATIONS, FORBIDDEN_CLAIMS };
