# logfilename owner:group mode count size(KB) when flags command
/Users/dan/pump-cost-accounting-system/logs/api-launchd*.log dan:staff 640 14 10240 * GEJR /usr/local/libexec/pumpfactory-api-log-reopen
/Users/dan/pump-cost-accounting-system/logs/web-launchd*.log dan:staff 640 14 10240 * GEJR /usr/local/libexec/pumpfactory-web-log-reopen
