# logfilename owner:group mode count size(KB) when flags pidfile signal
/Users/dan/pump-cost-accounting-system/logs/api-launchd*.log dan:staff 640 14 10240 * GJ /Users/dan/pump-cost-accounting-system/logs/api-launchd.pid 15
/Users/dan/pump-cost-accounting-system/logs/web-launchd*.log dan:staff 640 14 10240 * GJ /Users/dan/pump-cost-accounting-system/logs/web-launchd.pid 15
